name: Build/release Electron app

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm install

      - name: build-win
        run: npm run build:win
